"""Runtime inference — features → Live2D parameter values.

Self-contained: no dependency on portrait-to-live2d. The checkpoint (.pt)
is generated by portrait-to-live2d and consumed here as an artifact.

Supports two checkpoint formats:
  New (self-describing): dict with keys state_dict, input_dim, n_params, param_names
  Legacy (plain state_dict): hiyori_v2 — pass param_ids explicitly

Loads once at startup; predict() runs in <16ms on CPU.
"""
from __future__ import annotations

import json
import time
from pathlib import Path

import numpy as np
import torch

from muse_vtuber.mlp.model import CartoonAliveMLP


def _param_ids_from_model3(model3_json: Path) -> list[str]:
    """Read parameter IDs from a Live2D .model3.json file."""
    cdi3 = model3_json.with_suffix("").with_suffix(".cdi3.json")
    if cdi3.exists():
        cdi = json.loads(cdi3.read_text())
        return [p["Id"] for p in cdi.get("Parameters", [])]
    raise FileNotFoundError(f"No .cdi3.json found alongside {model3_json}")


class Predictor:
    """Wraps a loaded CartoonAliveMLP for repeated inference calls.

    Accepts either:
      - New self-describing checkpoint (humanoid-anime-bs58 style):
          Predictor(checkpoint)
      - Legacy plain state_dict (hiyori_v2 style):
          Predictor(checkpoint, param_ids=[...])
          Predictor.from_model3(checkpoint, model3_json)
    """

    def __init__(self, checkpoint: Path, param_ids: list[str] | None = None) -> None:
        ckpt = torch.load(checkpoint, map_location="cpu", weights_only=False)

        if isinstance(ckpt, dict) and "state_dict" in ckpt:
            # New self-describing format
            state = ckpt["state_dict"]
            input_dim = int(ckpt["input_dim"])
            self._param_ids: list[str] = list(ckpt["param_names"])
        else:
            # Legacy plain state_dict (hiyori_v2)
            if param_ids is None:
                raise ValueError(
                    "param_ids required for legacy plain-state_dict checkpoints"
                )
            state = ckpt
            input_dim = int(state["fc1.weight"].shape[1])
            self._param_ids = list(param_ids)

        self._input_dim = input_dim
        self._model = CartoonAliveMLP(n_params=len(self._param_ids), input_dim=input_dim)
        self._model.load_state_dict(state)
        self._model.eval()

    @classmethod
    def from_model3(cls, checkpoint: Path, model3_json: Path) -> "Predictor":
        """Construct by reading param IDs from the rig's .cdi3.json (legacy use)."""
        param_ids = _param_ids_from_model3(model3_json)
        return cls(checkpoint, param_ids)

    def predict(self, features: np.ndarray) -> dict[str, float]:
        """Map feature vector → {param_id: value}.

        Args:
            features: float32 array, shape (input_dim,) or matching checkpoint.
                      - New checkpoints: (58,) blendshapes+pose
                      - Legacy checkpoints: (478, 2) or (956,) landmarks
        """
        flat = features.reshape(1, self._input_dim).astype(np.float32)
        x = torch.from_numpy(flat)
        with torch.no_grad():
            y = self._model(x)
        return dict(zip(self._param_ids, y.squeeze(0).tolist()))

    def benchmark(self, n: int = 200) -> float:
        """Return mean inference time in ms over n runs."""
        dummy = np.zeros(self._input_dim, dtype=np.float32)
        for _ in range(10):
            self.predict(dummy)
        start = time.perf_counter()
        for _ in range(n):
            self.predict(dummy)
        return (time.perf_counter() - start) / n * 1000
