"""Runtime inference — landmarks → Live2D parameter values.

Self-contained: no dependency on portrait-to-live2d. The checkpoint (.pt)
is generated by portrait-to-live2d and consumed here as an artifact.

Loads once at startup; predict() runs in <16ms on CPU.
"""
from __future__ import annotations

import json
import time
from pathlib import Path

import numpy as np
import torch

from muse_vtuber.mlp.model import CartoonAliveMLP


def _param_ids_from_model3(model3_json: Path) -> list[str]:
    """Read parameter IDs from a Live2D .model3.json file."""
    # model3.json does not list params — read from adjacent .cdi3.json
    cdi3 = model3_json.with_suffix("").with_suffix(".cdi3.json")
    if cdi3.exists():
        cdi = json.loads(cdi3.read_text())
        return [p["Id"] for p in cdi.get("Parameters", [])]
    raise FileNotFoundError(f"No .cdi3.json found alongside {model3_json}")


class Predictor:
    """Wraps a loaded CartoonAliveMLP for repeated inference calls."""

    def __init__(self, checkpoint: Path, param_ids: list[str]) -> None:
        self._param_ids = param_ids
        self._model = CartoonAliveMLP(n_params=len(param_ids))
        state = torch.load(checkpoint, map_location="cpu", weights_only=False)
        self._model.load_state_dict(state)
        self._model.eval()

    @classmethod
    def from_model3(cls, checkpoint: Path, model3_json: Path) -> "Predictor":
        """Construct by reading param IDs from the rig's model3.json."""
        param_ids = _param_ids_from_model3(model3_json)
        return cls(checkpoint, param_ids)

    def predict(self, landmarks: np.ndarray) -> dict[str, float]:
        """Map 478 (x,y) landmarks → {param_id: value}.

        Args:
            landmarks: float32 array of shape (478, 2) or (956,).
        """
        flat = landmarks.reshape(1, 956).astype(np.float32)
        x = torch.from_numpy(flat)
        with torch.no_grad():
            y = self._model(x)
        values = y.squeeze(0).numpy()
        return dict(zip(self._param_ids, values.tolist()))

    def benchmark(self, n: int = 200) -> float:
        """Return mean inference time in ms over n runs."""
        dummy = np.zeros((478, 2), dtype=np.float32)
        for _ in range(10):
            self.predict(dummy)
        start = time.perf_counter()
        for _ in range(n):
            self.predict(dummy)
        return (time.perf_counter() - start) / n * 1000
