"""Face tracking → VTube Studio parameter bridge.

Webcam → MediaPipe → CartoonAlive MLP → VTS InjectParameterData at ~30fps.
Runs as an asyncio task alongside the BCI pipeline.

Checkpoint (.pt) is generated by portrait-to-live2d and placed at the path
configured in AppConfig.face_tracking_checkpoint.
"""
from __future__ import annotations

import asyncio
import json
import logging
from pathlib import Path

import websockets

from muse_vtuber.mlp.infer import Predictor
from muse_vtuber.outputs.face_tracking import landmark_stream

log = logging.getLogger(__name__)

_TOKEN_FILE = Path.home() / ".config" / "muse-vtuber" / "face_tracking_vts_token.txt"
_PLUGIN_NAME = "muse-vtuber-face"
_PLUGIN_DEVELOPER = "muse-vtuber"


async def _authenticate(ws) -> None:
    _TOKEN_FILE.parent.mkdir(parents=True, exist_ok=True)
    saved = _TOKEN_FILE.read_text().strip() if _TOKEN_FILE.exists() else ""

    req = {
        "apiName": "VTubeStudioPublicAPI", "apiVersion": "1.0",
        "requestID": "auth", "messageType": "AuthenticationRequest",
        "data": {
            "pluginName": _PLUGIN_NAME, "pluginDeveloper": _PLUGIN_DEVELOPER,
            "authenticationToken": saved,
        },
    }
    await ws.send(json.dumps(req))
    resp = json.loads(await ws.recv())
    if resp["data"].get("authenticated"):
        log.info("face_params: VTS authenticated")
        return

    token_req = {
        "apiName": "VTubeStudioPublicAPI", "apiVersion": "1.0",
        "requestID": "token", "messageType": "AuthenticationTokenRequest",
        "data": {"pluginName": _PLUGIN_NAME, "pluginDeveloper": _PLUGIN_DEVELOPER},
    }
    await ws.send(json.dumps(token_req))
    token_resp = json.loads(await ws.recv())
    token = token_resp["data"]["authenticationToken"]
    _TOKEN_FILE.write_text(token)

    req["data"]["authenticationToken"] = token
    await ws.send(json.dumps(req))
    final = json.loads(await ws.recv())
    if not final["data"].get("authenticated"):
        raise RuntimeError("face_params: VTS auth failed after token request")
    log.info("face_params: VTS authenticated (new token)")


async def _inject(ws, params: dict[str, float]) -> None:
    payload = {
        "apiName": "VTubeStudioPublicAPI", "apiVersion": "1.0",
        "requestID": "inject", "messageType": "InjectParameterDataRequest",
        "data": {
            "faceFound": True, "mode": "set",
            "parameterValues": [{"id": k, "value": float(v)} for k, v in params.items()],
        },
    }
    await ws.send(json.dumps(payload))
    await ws.recv()


async def run(
    predictor: Predictor,
    camera_index: int = 0,
    vts_port: int = 8001,
) -> None:
    """Main loop: webcam → MLP → VTS. Reconnects on disconnect."""
    url = f"ws://localhost:{vts_port}"
    while True:
        try:
            async with websockets.connect(url) as ws:
                await _authenticate(ws)
                log.info("face_params: streaming camera %d → VTS %s", camera_index, url)
                async for landmarks in landmark_stream(camera_index=camera_index):
                    params = predictor.predict(landmarks)
                    await _inject(ws, params)
        except (OSError, websockets.ConnectionClosed) as e:
            log.warning("face_params: VTS lost (%s), retrying in 3s", e)
            await asyncio.sleep(3)
